import Groq from 'groq-sdk';


const getAI = () => {
  const apiKey = import.meta.env.VITE_GROQ_API_KEY;
  if (!apiKey) return null;
  return new Groq({ apiKey, dangerouslyAllowBrowser: true });
};

const SYSTEM_PROMPT = `
You are a Senior QA & Automation Engineer Agent. Your job is to rigorously test the code repository generated by the Developer Agent.

### Responsibilities:
1. **Code Review**: Check for syntax errors, missing imports, and logic flaws.
2. **Standard Compliance**: Ensure the project follows the requested MVP features and tech stack.
3. **Debug & Feedback**: If errors are found, provide DETAILED feedback on exactly what needs to be fixed.
4. **Iterative Loops**: Your feedback will be used by the Developer Agent to correct the code.

### Output JSON Schema:
{
  "test_cases": [
    { "id": "number", "test_name": "string", "description": "string", "status": "passed|failed", "feedback": "string" }
  ],
  "summary": "string",
  "has_errors": "boolean",
  "feedback_for_developer": "string (Detailed instructions for the developer if has_errors is true)"
}

Keep your feedback actionable and precise. Only return the JSON object.
`;

const MODEL_CANDIDATES = ['llama-3.3-70b-versatile', 'llama-3.1-70b-versatile'];

export async function runTesterAgent(repoJson: string, projectContext: string, signal?: AbortSignal): Promise<string> {
  const groq = getAI();
  const fallbackResults = JSON.stringify({
    test_cases: [
      { id: 1, test_name: "Basic Validation", description: "Checking if repo exists", status: "passed", feedback: "Repo generated." }
    ],
    summary: "Basic verification complete. No critical errors found in fallback mode.",
    has_errors: false,
    feedback_for_developer: ""
  });

  if (!groq) return fallbackResults;

  const prompt = `
### Project Context
${projectContext}

### Generated Repository (JSON)
${repoJson}

### Task
Perform a comprehensive test of the repository above. Identify any bugs, missing files, or logic errors. 
Provide a clear list of passed/failed cases and detailed feedback for the developer if corrections are needed.
  `;

  for (const model of MODEL_CANDIDATES) {
    try {
      const chatCompletion = await groq.chat.completions.create({
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: prompt }
        ],
        model,
        temperature: 0.2,
        response_format: { type: 'json_object' }
      }, { signal });
      
      const text = chatCompletion.choices[0]?.message?.content || '';
      if (text) return text;
    } catch (err: any) {
      console.error(`Tester Generation Error (${model}):`, err);
    }
  }

  return fallbackResults;
}
